app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function (Request $request) {
	$data = [
		'request'=>$request
	];
    return view('laravel.login', $data);
});*/

Route::get('/', ['as' =>'login_page','uses' => 'Auth\AuthController@getLogin']);
Route::post('/', ['as' =>'login_auth','uses' => 'Auth\AuthController@postLogin']);

//	Portal
Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function(){
	Route::get('/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);
	Route::get('/',['as' =>'dashboard','uses' => 'DashboardController@index']);
	

	//	Password Reset
	Route::group(['prefix' => 'password-reset'], function(){
		Route::get('/',['as' =>'reset_password','uses' => 'UserController@reset_password']);
		Route::post('/',['as' =>'password_reset','uses' => 'UserController@password_reset']);
	});// Password Reset

	//	Enrolment
	Route::group(['prefix' => 'enrolment'], function(){
		// Search Item
		Route::get('/search-item',['as' =>'search_item', 'uses' => 'ItemController@search']);
		// Search Physician
		Route::get('/search-physician',['as' =>'search_physician','uses' => 'UserController@search_physician']);
		// Search VCT Patient
		Route::get('/search-patient',['as' =>'search_vct_patient','uses' => 'VCTController@search_patient']);
		// Get Patient Record on VCT
		Route::get('/vct-record',['as' =>'vct_record','uses' => 'VCTController@vct_record']);
		// Search Demographics Patient
		Route::get('/search-demographics-patient',['as' =>'search_demographics_patient','uses' => 'DemographicsController@search_patient']);
		
		//	VCT
		Route::group(['prefix' => 'vct'], function(){
			Route::get('/',['as' =>'vct_index','uses' => 'VCTController@index']);
					
			Route::get('/create',['as' =>'vct_create', 'uses' => 'VCTController@create']);
			Route::post('/store',['as' =>'vct_store', 'uses' => 'VCTController@store']);
					
			Route::get('/edit/{id}',['as' =>'vct_edit', 'uses' => 'VCTController@edit']);
			Route::post('/update/{id}',['as' =>'vct_update', 'uses' => 'VCTController@update']);
		});// VCT
		//	Demographics
		Route::group(['prefix' => 'demographics'], function(){
			Route::get('/',['as' =>'demographics_index','uses' => 'DemographicsController@index']);
					
			Route::get('/create',['as' =>'demographics_create', 'uses' => 'DemographicsController@create']);
			Route::post('/store',['as' =>'demographics_store', 'uses' => 'DemographicsController@store']);
					
			Route::get('/edit/{id}',['as' =>'demographics_edit', 'uses' => 'DemographicsController@edit']);
			Route::post('/update/{id}',['as' =>'demographics_update', 'uses' => 'DemographicsController@update']);
		});// Demographics
		//	Clinical and Immunological Profile
		Route::group(['prefix' => 'clinical-and-immunologic-profile'], function(){
			Route::get('/',['as' =>'caip_index','uses' => 'ClinicalAndImmunologicProfileController@index']);
			Route::get('/show/{id}',['as' =>'caip_show', 'uses' => 'ClinicalAndImmunologicProfileController@show']);	
					
			Route::get('/create/{id?}',['as' =>'caip_create', 'uses' => 'ClinicalAndImmunologicProfileController@create']);
			Route::post('/store',['as' =>'caip_store', 'uses' => 'ClinicalAndImmunologicProfileController@store']);	

			Route::get('/edit/{id}',['as' =>'caip_edit', 'uses' => 'ClinicalAndImmunologicProfileController@edit']);
			Route::post('/update/{id}',['as' =>'caip_update', 'uses' => 'ClinicalAndImmunologicProfileController@update']);

			Route::get('/destroy/{id}',['as' =>'caip_destroy', 'uses' => 'ClinicalAndImmunologicProfileController@destroy']);
		});// Clinical and Immunological Profile
		//	Opportunistic Infections Profile
		Route::group(['prefix' => 'opportunistic-infections-profile'], function(){
			Route::get('/',['as' =>'oi_profile_index','uses' => 'OpportunisticInfectionsProfileController@index']);
			Route::get('/show/{id}',['as' =>'oi_profile_show', 'uses' => 'OpportunisticInfectionsProfileController@show']);
					
			Route::get('/create',['as' =>'oi_profile_create', 'uses' => 'OpportunisticInfectionsProfileController@create']);
			Route::post('/store',['as' =>'oi_profile_store', 'uses' => 'OpportunisticInfectionsProfileController@store']);
					
			Route::get('/edit/{id}',['as' =>'oi_profile_edit', 'uses' => 'OpportunisticInfectionsProfileController@edit']);
			Route::post('/update/{id}',['as' =>'oi_profile_update', 'uses' => 'OpportunisticInfectionsProfileController@update']);
		});// Medication Profile
		//	Medication Profile
		Route::group(['prefix' => 'medication-profile'], function(){
			Route::get('/',['as' =>'medication_index','uses' => 'MedicationProfileController@index']);
			Route::get('/show/{id}',['as' =>'medication_show', 'uses' => 'MedicationProfileController@show']);		
					
			Route::get('/create/{id?}',['as' =>'medication_create', 'uses' => 'MedicationProfileController@create']);
			Route::post('/store',['as' =>'medication_store', 'uses' => 'MedicationProfileController@store']);
					
			Route::get('/edit/{id}',['as' =>'medication_edit', 'uses' => 'MedicationProfileController@edit']);
			Route::post('/update/{id}',['as' =>'medication_update', 'uses' => 'MedicationProfileController@update']);

			Route::get('/edit-stop/{id}',['as' =>'medication_edit_stop', 'uses' => 'MedicationProfileController@edit_stop']);
			Route::post('/update-stop/{id}',['as' =>'medication_update_stop', 'uses' => 'MedicationProfileController@update_stop']);

			Route::get('/destroy/{id}',['as' =>'medication_destroy', 'uses' => 'MedicationProfileController@destroy']);	
			Route::get('/continue-medication/{id}',['as' =>'medication_continue', 'uses' => 'MedicationProfileController@continue_medication']);			
		});// Medication Profile

	});// Enrolment

	//	Event
	Route::group(['prefix' => 'event'], function(){
		//ARV
		Route::group(['prefix' => 'arv'], function(){
			Route::get('/',['as' => 'arv_index','uses' => 'ARVController@index']);
			Route::get('/show/{id}',['as' =>'arv_show', 'uses' => 'ARVController@show']);

			Route::get('/create/{id?}', ['as' => 'arv_create', 'uses' => 'ARVController@create']);
			Route::post('/store', ['as' => 'arv_store', 'uses' => 'ARVController@store']);
					
			Route::get('/edit/{id}',['as' => 'arv_edit', 'uses' => 'ARVController@edit']);
			Route::post('/update/{id}',['as' => 'arv_update', 'uses' => 'ARVController@update']);
		});	//ARV

		//	ARV Refill
		Route::group(['prefix' => 'arv-refill'], function(){
			Route::get('/',['as' => 'arv_refill_index','uses' => 'ARVRefillController@index']);
					
			Route::get('/create',['as' => 'arv_refill_create', 'uses' => 'ARVRefillController@create']);
			Route::post('/store',['as' => 'arv_refill_store', 'uses' => 'ARVRefillController@store']);
					
			Route::get('/edit/{id}',['as' => 'arv_refill_edit', 'uses' => 'ARVRefillController@edit']);
			Route::post('/update/{id}',['as' => 'arv_refill_update', 'uses' => 'ARVRefillController@update']);
		});// ARV Refill
		// Check UP
		Route::group(['prefix' => 'check-up'], function(){
			Route::get('/', ['as' => 'checkup_index', 'uses' => 'CheckUpController@index']);
			Route::get('/create', ['as' => 'checkup_create', 'uses' => 'CheckUpController@create']);
			Route::post('/store', ['as' => 'checkup_store', 'uses' => 'CheckUpController@store']);
			Route::get('/edit/{id}', ['as' => 'checkup_edit', 'uses' => 'CheckUpController@edit']);
			Route::post('/update/{id}', ['as' => 'checkup_update', 'uses' => 'CheckUpController@update']);
			Route::get('/show/{id}', ['as' => 'checkup_show', 'uses' => 'CheckUpController@show']);
		});// Check UP

		//	Death
		Route::group(['prefix' => 'death'], function(){
			Route::get('/',['as' => 'death_index','uses' => 'DeathController@index']);

			Route::get('/create', ['as' => 'death_create', 'uses' => 'DeathController@create']);
			Route::post('/store', ['as' => 'death_store', 'uses' => 'DeathController@store']);
					
			Route::get('/edit/{id}',['as' => 'death_edit', 'uses' => 'DeathController@edit']);
			Route::post('/update/{id}',['as' => 'death_update', 'uses' => 'DeathController@update']);
		});	//ARV

	});// Event

	//	Reports
	Route::group(['prefix' => 'reports'], function(){
		Route::get('/form-b/{id?}',['as' =>'form_b','uses' => 'PrintFormsController@form_b']);
		Route::get('/form-c/{id?}',['as' =>'form_c','uses' => 'PrintFormsController@form_c']);
		Route::get('/form-d/{id?}',['as' =>'form_d','uses' => 'PrintFormsController@form_d']);
	});// Password Reset

	//	Item
	Route::group(['prefix' => 'item'], function(){
		Route::get('/',['as' =>'item_list', 'uses' => 'ItemController@index']);
			
		Route::get('/create',['as' =>'item_create','uses' => 'ItemController@create']);
		Route::post('/store',['as' =>'item_store','uses' => 'ItemController@store']);

		Route::get('/edit/{id}',['as' =>'item_edit','uses' => 'ItemController@edit']);
		Route::post('/update/{id}',['as' =>'item_update','uses' => 'ItemController@update']);

		Route::get('/destroy/{id}',['as' =>'item_destroy','uses' => 'ItemController@destroy']);

		/*
		//	Category
		Route::group(['prefix' => 'category'], function(){
			Route::get('/',['as' =>'item_category_list','uses' => 'ItemCategoryController@index']);

			Route::get('/create',['as' =>'item_category_create','uses' => 'ItemCategoryController@create']);
			Route::post('/store',['as' =>'item_category_store','uses' => 'ItemCategoryController@store']);

			Route::get('/edit/{id}',['as' =>'item_category_edit','uses' => 'ItemCategoryController@edit']);
			Route::post('/update/{id}',['as' =>'item_category_update','uses' => 'ItemCategoryController@update']);

		});// Category
		*/

		//	Receive
		Route::group(['prefix' => 'receive'], function(){

app/VCT.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VCT extends Model
{
    protected $table = 'vct';

    public $timestamps = false;

    /*
    Relationships
    */

    public function EnrolmentDemographics()
    {
        return $this->belongsTo('App\EnrolmentDemographics', 'id', 'id');
    }

    public function EnrolmentClinicalAndImmunologic()
    {
        return $this->belongsTo('App\EnrolmentClinicalAndImmunologic', 'id', 'id');
    }

    public function OpportunisticInfections()
    {
        return $this->belongsTo('App\OpportunisticInfections', 'id', 'id');
    }

    /*
    Set Functions
    */

    public function setUiCodeAttribute($value)
    {
        $this->attributes['ui_code'] = strtoupper($value);
    }

    public function setHivPositiveDateRetestAttribute($value)
    {
        if(is_null($value)){
            $value = null;
        }else{
            $value = date('Y-m-d', strtotime($value));
        }

        $this->attributes['hiv_positive_date_retest'] = $value;
    }

    /*
    Get Functions
    */

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getFullName2Attribute()
    {
        return $this->last_name . ', ' . $this->first_name;
    }

    public function getGenderAttribute($value)
    {
        return ucwords($value);
    }

    public function getBirthDateAttribute($value)
    {
        return date('F d, Y', strtotime($value));
    }

    public function getHivPositiveFormatAttribute()
    {
        if($this->hiv_positive){
            return 'Yes';
        }else{
            return 'No';
        }
    }
    /*
    Other Functions
    */

    public function scopeSearchVctList($query, $search)
    {
        $search = '%' . $search . '%';

        return $query->where('first_name', 'LIKE', $search)
                    ->orWhere('last_name', 'LIKE', $search)
                    ->orWhere('ui_code', 'LIKE', $search)
                    ->orWhere('gender', 'LIKE', $search)
                    ->orWhere('vct_date', 'LIKE', $search);
    }

    public function maleCapital()
    {
    	return strtoupper($this->gender);
    }
}

resources/views/hact/enrolment/medication-profile/create.blade.php
@extends('hact.layouts.layout_admin')

@section('content')

    <div class='row'>
        <div class='large-12 columns'>
            <ul class="breadcrumbs">
                <li><a href="{{ route('dashboard') }}">Home</a></li>
                <li><a href="{{ route('medication_index') }}">Medication</a></li>
                <li class="current"><a href="#">New Record</a></li>
            </ul>
        </div>
    </div>

	@include('hact.messages.success')
	@include('hact.messages.error_list')

    <div class="panel">
    	<form action="{{ $action }}" method="post">
            <fieldset>
                <legend>Patient's Name</legend>
                <div class="row">
                    <div class="large-6 columns">
                        <div class="row collapse">
                            <div class="small-10 columns">
                                <input type="text" id="search_patient" name="search_patient" placeholder="Search Patient" value="{{ $search_patient }}">
                                <input type="hidden" id="demographics_id" name="demographics_id" value="{{ $demographics_id }}" />
                                <input type="hidden" id="search_patient_url" name="search_patient_url" value="{{ route('search_demographics_patient') }}" />
                            </div>
                            <div class="small-2 columns">
                                <span class="postfix"><i class="fa fa-search"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
    		<fieldset>
        		<legend>Medications Profile</legend>
        		<div class="row">
        			<div class="large-6 columns">
    					<div class="row">
    						<div class="large-12 columns">
    							<label for="medication_name">Name of Medication:</label>
    							<input type="text" id="item_search" name="search_item" placeholder="Search Medication" value="{{ $search_item }}" />
                                <input type="hidden" id="item_id" name="item_id" value="{{ $item_id }}" />
                                <input type="hidden" id="search_item_url" name="search_item_url" value="{{ route('search_item') }}" />
    						</div>
    					</div>
    					<div class="row">
    						<div class="large-12 columns">
    							<label for="dosage">Dosage:</label>
    							<input type="text" id="dosage" name="dosage" placeholder="Dosage" value="{{ $dosage }}" />
    						</div>
    					</div>
        			</div>
        			<div class="large-6 columns">
    					<div class="row">
    						<div class="large-12 columns">
    							<label for="frequency">Frequency:</label>
    							<input type="text" id="frequency" name="frequency" placeholder="Frequency" value="{{ $frequency }}" />
    						</div>
    					</div>
    					<div class="row">
    						<div class="large-12 columns">
    							<label for="date_started">Date Started:</label>
    							<input type="text" id="date_started" name="date_started" placeholder="Date Started" value="{{ $date_started }}" class="fdatepicker" readonly="readonly" />
    						</div>
    					</div>
        			</div>
        		</div>
    		</fieldset><br/>

    		<div class="row">
    			<div class="large-4 columns">&nbsp;</div>
    			<div class="large-4 columns">
                    <div class="row">
                        <div class="large-3 columns">&nbsp;</div>
                        <div class="large-6 columns">
                            {!! csrf_field() !!}
                            <input type="submit" class="button alert expand" value="Submit">
                        </div>
                        <div class="large-3 columns">&nbsp;</div>
                    </div>
    			</div>
    			<div class="large-4 columns">&nbsp;</div>
    		</div>
    	</form>
    </div>
<script type="text/javascript">


$(function(){
    $("#occupational_exposure").click(function(){
        var status = $(this).is(':checked');

        if(status == true)
        {
        	$('.occupational_exposure_selection').show();
        }
        else
        {
        	$('.occupational_exposure_selection').hide();
        }
    });
});
</script>

@endsection

resources/views/hact/enrolment/medication-profile/index.blade.php
@extends('hact.layouts.layout_admin')

@section('content')

	<div class='row'>
		<div class='large-7 columns'>
			<ul class="breadcrumbs">
				<li><a href="{{ route('dashboard') }}">Home</a></li>
				<li class="current"><a href="#">Medication</a></li>
			</ul>
		</div>
		<div class='large-5 columns'>
			<form>
				<div class="row">
					<div class="large-12 columns">
						<div class="row collapse">
							<div class="small-9 columns">
								<input name="search" type="text" placeholder="Search" value="{{ $search }}">
							</div>
					    	<div class="small-3 columns">
					      		<button type="submit" class="button alert postfix"><i class="fa fa-search"></i></buatton>
					    	</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
	
	<div class='row'>
		<div class='large-12 columns'>
			{!! str_replace('/?', '?', $patients->appends($pagination)->render()) !!}
			<table width="100%">
				<thead>
					<tr>
						<th width="10%"></th>

						<th width="20%"><a href="{{ $ui_code_sort }}">UI Code</a></th>
						<th width="20%"><a href="{{ $code_name_sort }}">Code Name</a></th>
						<th width="20%"><a href="{{ $saccl_code_sort }}">SACCL</a></th>
						<th width="30%"><a href="{{ $last_name_sort }}">Name</a></th>

					</tr>
				</thead>
				<tbody>
				@foreach($patients as $patient)
				<tr>
					<td>
						<a title="Medication Profile" href="{{ route('medication_show',[$patient->id]) }}"><i class="fa fa-user fa-lg"></i></a>
						<a title="New Medication Record" href="{{ route('medication_create', $patient->id) }}"><i class="fa fa-plus fa-lg"></i></a>
					</td>
					<td>{{ $patient->ui_code }}</td>
					<td>{{ $patient->code_name }}</td>
					<td>{{ $patient->saccl_code }}</td>
					<td>{{ $patient->full_name2  }}</td>
				</tr>
				@endforeach	
				</tbody>
			</table>
			{!! str_replace('/?', '?', $patients->appends($pagination)->render()) !!}
		</div>
	</div>

@endsection

resources/views/hact/enrolment/medication-profile/show.blade.php
@extends('hact.layouts.layout_admin')

@section('content')

    <div class='row'>
        <div class='large-12 columns'>
            <ul class="breadcrumbs">
                <li><a href="{{ route('dashboard') }}">Home</a></li>
                <li><a href="{{ route('medication_index') }}">Medication</a></li>
                <li class="current"><a href="#">{{ $patient->full_name }}</a></li>
            </ul>
        </div>
    </div>

	<div class='row'>
		<div class="large-12 columns">
			<a title="add medication" href="{{ route('medication_create', $patient->id) }}"><i class="fa fa-2x fa-plus-circle"></i></a>
		</div>
    </div>

	<div class='row'>
		<div class='large-12 columns'>
			@include('hact.messages.success')
			@include('hact.messages.error_list')
			{!! str_replace('/?', '?', $medications->render()) !!}
			<table width="100%">
				<thead>
					<tr>
						<th width="10%" rowspan="2"></th>
						<th width="25%" rowspan="2">Medicine Name</th>
						<th width="10%" rowspan="2">Dosage</th>
						<th width="10%" rowspan="2">Frequency</th>
						<th colspan="2" class="text-center">Date</th>
						<th width="25%" rowspan="2">Reason for Discontinuation</th>
					</tr>
					<tr>
						<th width="10%">Started</th>
						<th width="10%">Discontinued</th>
					</tr>
				</thead>
				<tbody>
				@foreach($medications as $medication)
					<tr>
						<td>
							<a title="Edit Medication" href="{{ route('medication_edit', $medication->medication_id) }}"><i class="fa fa-edit fa-lg"></i></a>
							<a title="Stop Medication" href="{{ route('medication_edit_stop', [$medication->medication_id]) }}"><i class="fa fa-hand-paper-o fa-lg"></i></a>
						</td>
						<td>{{ $medication->Item->item_name }}</td>
						<td>{{ $medication->dosage  }}</td>
						<td>{{ $medication->frequency  }}</td>
						<td>{{ $medication->date_started  }}</td>
						<td>{{ $medication->date_discontinued  }}</td>
						<td>{{ $medication->discontinuation_reason  }}</td>
					</tr>
				@endforeach
				</tbody>
			</table>
			{!! str_replace('/?', '?', $medications->render()) !!}
		</div>
	</div>

@endsection

resources/views/hact/enrolment/medication-profile/stop.blade.php
@extends('hact.layouts.layout_admin')

@section('content')

    <div class='row'>
        <div class='large-12 columns'>
            <h3>Medication Discontinuation</h3>
            <hr />
        </div>
    </div>

	@include('hact.messages.success')
	@include('hact.messages.error_list')

	<form action="{{ $action }}" method="post">

		<fieldset>
    		<legend>Medications Profile</legend><br/>
            <div class="row">
                <div class="large-5 columns">
                    <label for="search_patient">Patient:</label>
                    <input type="text" id="search_patient" name="search_patient" placeholder="Search Patient" value="{{ $search_patient }}" readonly="readonly" />
                    <input type="hidden" id="demographics_id" name="demographics_id" value="{{ $demographics_id }}" />
                    <input type="hidden" id="search_patient_url" name="search_patient_url" value="{{ route('search_demographics_patient') }}" />
                </div>
                <div class="large-7 columns">
                    <label for="medication_name">Name of Medication:</label>
                    <input type="text" id="item_search" name="search_item" placeholder="Search Medication" value="{{ $search_item }}" readonly="readonly" />
                    <input type="hidden" id="item_id" name="item_id" value="{{ $item_id }}" />
                    <input type="hidden" id="search_item_url" name="search_item_url" value="{{ route('search_item') }}" />
                </div>
            </div>
            <div class="row">
                <div class="large-5 columns">
                    <label for="dosage">Dosage:</label>
                    <input type="text" id="dosage" name="dosage" placeholder="Dosage" value="{{ $dosage }}" class="fdatepicker" readonly="readonly" />
                </div>
                <div class="large-7 columns">
                    <label for="frequency">Frequency:</label>
                    <input type="text" id="frequency" name="frequency" placeholder="Frequency" value="{{ $frequency }}" readonly="readonly" />
                </div>
            </div>
            <div class="row">
                <div class="large-5 columns">
                    <label for="date_started">Date Started:</label>
                    <input type="text" id="date_started" name="date_started" placeholder="Date Started" value="{{ $date_started }}" readonly="readonly" />
                </div>
                <div class="large-7 columns">&nbsp;</div>
            </div>
            <div class="row">
                <div class="large-5 columns">
                    <label for="date_discontinued">Date Discontinued:</label>
                    <input type="text" id="date_discontinued" name="date_discontinued" placeholder="Date Discontinued" value="{{ $date_discontinued }}" class="fdatepicker" readonly="readonly" />
                </div>
                <div class="large-7 columns">
                    <label for="discontinuation_reason">Reason for Discontinuation:</label>
                    <input type="text" id="discontinuation_reason" name="discontinuation_reason" placeholder="Reason for Discontinuation" value="{{ $discontinuation_reason }}" />
                </div>
            </div>
		</fieldset><br/>

		<div class="row">
			<div class="large-4 columns">&nbsp;</div>
			<div class="large-4 columns">
				<input type="submit" class="button expand" value="Submit">
			</div>
			<div class="large-4 columns">&nbsp;</div>
		</div>
		{!! csrf_field() !!}
	</form>

<script type="text/javascript">

var xhr_patient_search = null;
var xhr_patient_record = null;
$(function(){
    $("#search_patient").autocomplete({
        source: function (request, response) 
        {
            xhr_patient_search = $.ajax({
                type : 'get',
                url : $("#search_patient_url").val(),
                data : 'search_patient=' + request.term,
                cache : false,
                dataType : "json",
                beforeSend: function(xhr) 
                {
                    if (xhr_patient_search != null)
                    {
                        xhr_patient_search.abort();
                    }
                }
            }).done(function(data){
                response($.map( data, function(value, key) 
                {
                    return { label: value, value: key }
                }));

            }).fail(function(jqXHR, textStatus){
                //console.log('Request failed: ' + textStatus);
            });
        }, 
        minLength: 2,
        autoFocus: true,
        select: function(a, b)
        {
            var id = b.item.value;
            var name = b.item.label;

            $('#demographics_id').val(id);
            $('#search_patient').val(name).focus();

            return false;
        }
    });
});
</script>

@endsection