app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function (Request $request) {
	$data = [
		'request'=>$request
	];
    return view('laravel.login', $data);
});*/

Route::get('/', ['as' =>'login_page','uses' => 'Auth\AuthController@getLogin']);
Route::post('/', ['as' =>'login_auth','uses' => 'Auth\AuthController@postLogin']);

//	Portal
Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function(){
	Route::get('/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);
	Route::get('/',['as' =>'dashboard','uses' => 'DashboardController@index']);
	

	//	Password Reset
	Route::group(['prefix' => 'password-reset'], function(){
		Route::get('/',['as' =>'reset_password','uses' => 'UserController@reset_password']);
		Route::post('/',['as' =>'password_reset','uses' => 'UserController@password_reset']);
	});// Password Reset

	//	Enrolment
	Route::group(['prefix' => 'enrolment'], function(){
		// Search Item
		Route::get('/search-item',['as' =>'search_item', 'uses' => 'ItemController@search']);
		// Search Physician
		Route::get('/search-physician',['as' =>'search_physician','uses' => 'UserController@search_physician']);
		// Search VCT Patient
		Route::get('/search-patient',['as' =>'search_vct_patient','uses' => 'VCTController@search_patient']);
		// Get Patient Record on VCT
		Route::get('/vct-record',['as' =>'vct_record','uses' => 'VCTController@vct_record']);
		// Search Demographics Patient
		Route::get('/search-demographics-patient',['as' =>'search_demographics_patient','uses' => 'DemographicsController@search_patient']);
		
		//	VCT
		Route::group(['prefix' => 'vct'], function(){
			Route::get('/',['as' =>'vct_index','uses' => 'VCTController@index']);
					
			Route::get('/create',['as' =>'vct_create', 'uses' => 'VCTController@create']);
			Route::post('/store',['as' =>'vct_store', 'uses' => 'VCTController@store']);
					
			Route::get('/edit/{id}',['as' =>'vct_edit', 'uses' => 'VCTController@edit']);
			Route::post('/update/{id}',['as' =>'vct_update', 'uses' => 'VCTController@update']);
		});// VCT
		//	Demographics
		Route::group(['prefix' => 'demographics'], function(){
			Route::get('/',['as' =>'demographics_index','uses' => 'DemographicsController@index']);
					
			Route::get('/create',['as' =>'demographics_create', 'uses' => 'DemographicsController@create']);
			Route::post('/store',['as' =>'demographics_store', 'uses' => 'DemographicsController@store']);
					
			Route::get('/edit/{id}',['as' =>'demographics_edit', 'uses' => 'DemographicsController@edit']);
			Route::post('/update/{id}',['as' =>'demographics_update', 'uses' => 'DemographicsController@update']);
		});// Demographics
		//	Clinical and Immunological Profile
		Route::group(['prefix' => 'clinical-and-immunologic-profile'], function(){
			Route::get('/',['as' =>'caip_index','uses' => 'ClinicalAndImmunologicProfileController@index']);
			Route::get('/show/{id}',['as' =>'caip_show', 'uses' => 'ClinicalAndImmunologicProfileController@show']);	
					
			Route::get('/create/{id?}',['as' =>'caip_create', 'uses' => 'ClinicalAndImmunologicProfileController@create']);
			Route::post('/store',['as' =>'caip_store', 'uses' => 'ClinicalAndImmunologicProfileController@store']);	

			Route::get('/edit/{id}',['as' =>'caip_edit', 'uses' => 'ClinicalAndImmunologicProfileController@edit']);
			Route::post('/update/{id}',['as' =>'caip_update', 'uses' => 'ClinicalAndImmunologicProfileController@update']);

			Route::get('/destroy/{id}',['as' =>'caip_destroy', 'uses' => 'ClinicalAndImmunologicProfileController@destroy']);
		});// Clinical and Immunological Profile
		//	Opportunistic Infections Profile
		Route::group(['prefix' => 'opportunistic-infections-profile'], function(){
			Route::get('/',['as' =>'oi_profile_index','uses' => 'OpportunisticInfectionsProfileController@index']);
			Route::get('/show/{id}',['as' =>'oi_profile_show', 'uses' => 'OpportunisticInfectionsProfileController@show']);
					
			Route::get('/create',['as' =>'oi_profile_create', 'uses' => 'OpportunisticInfectionsProfileController@create']);
			Route::post('/store',['as' =>'oi_profile_store', 'uses' => 'OpportunisticInfectionsProfileController@store']);
					
			Route::get('/edit/{id}',['as' =>'oi_profile_edit', 'uses' => 'OpportunisticInfectionsProfileController@edit']);
			Route::post('/update/{id}',['as' =>'oi_profile_update', 'uses' => 'OpportunisticInfectionsProfileController@update']);
		});// Medication Profile
		//	Medication Profile
		Route::group(['prefix' => 'medication-profile'], function(){
			Route::get('/',['as' =>'medication_index','uses' => 'MedicationProfileController@index']);
			Route::get('/show/{id}',['as' =>'medication_show', 'uses' => 'MedicationProfileController@show']);		
					
			Route::get('/create/{id?}',['as' =>'medication_create', 'uses' => 'MedicationProfileController@create']);
			Route::post('/store',['as' =>'medication_store', 'uses' => 'MedicationProfileController@store']);
					
			Route::get('/edit/{id}',['as' =>'medication_edit', 'uses' => 'MedicationProfileController@edit']);
			Route::post('/update/{id}',['as' =>'medication_update', 'uses' => 'MedicationProfileController@update']);

			Route::get('/edit-stop/{id}',['as' =>'medication_edit_stop', 'uses' => 'MedicationProfileController@edit_stop']);
			Route::post('/update-stop/{id}',['as' =>'medication_update_stop', 'uses' => 'MedicationProfileController@update_stop']);

			Route::get('/destroy/{id}',['as' =>'medication_destroy', 'uses' => 'MedicationProfileController@destroy']);	
			Route::get('/continue-medication/{id}',['as' =>'medication_continue', 'uses' => 'MedicationProfileController@continue_medication']);			
		});// Medication Profile

	});// Enrolment

	//	Event
	Route::group(['prefix' => 'event'], function(){
		//ARV
		Route::group(['prefix' => 'arv'], function(){
			Route::get('/',['as' => 'arv_index','uses' => 'ARVController@index']);
			Route::get('/show/{id}',['as' =>'arv_show', 'uses' => 'ARVController@show']);

			Route::get('/create/{id?}', ['as' => 'arv_create', 'uses' => 'ARVController@create']);
			Route::post('/store', ['as' => 'arv_store', 'uses' => 'ARVController@store']);
					
			Route::get('/edit/{id}',['as' => 'arv_edit', 'uses' => 'ARVController@edit']);
			Route::post('/update/{id}',['as' => 'arv_update', 'uses' => 'ARVController@update']);
		});	//ARV

		//	ARV Refill
		Route::group(['prefix' => 'arv-refill'], function(){
			Route::get('/',['as' => 'arv_refill_index','uses' => 'ARVRefillController@index']);
					
			Route::get('/create',['as' => 'arv_refill_create', 'uses' => 'ARVRefillController@create']);
			Route::post('/store',['as' => 'arv_refill_store', 'uses' => 'ARVRefillController@store']);
					
			Route::get('/edit/{id}',['as' => 'arv_refill_edit', 'uses' => 'ARVRefillController@edit']);
			Route::post('/update/{id}',['as' => 'arv_refill_update', 'uses' => 'ARVRefillController@update']);
		});// ARV Refill
		// Check UP
		Route::group(['prefix' => 'check-up'], function(){
			Route::get('/', ['as' => 'checkup_index', 'uses' => 'CheckUpController@index']);
			Route::get('/create', ['as' => 'checkup_create', 'uses' => 'CheckUpController@create']);
			Route::post('/store', ['as' => 'checkup_store', 'uses' => 'CheckUpController@store']);
			Route::get('/edit/{id}', ['as' => 'checkup_edit', 'uses' => 'CheckUpController@edit']);
			Route::post('/update/{id}', ['as' => 'checkup_update', 'uses' => 'CheckUpController@update']);
			Route::get('/show/{id}', ['as' => 'checkup_show', 'uses' => 'CheckUpController@show']);
		});// Check UP

		//	Death
		Route::group(['prefix' => 'death'], function(){
			Route::get('/',['as' => 'death_index','uses' => 'DeathController@index']);

			Route::get('/create', ['as' => 'death_create', 'uses' => 'DeathController@create']);
			Route::post('/store', ['as' => 'death_store', 'uses' => 'DeathController@store']);
					
			Route::get('/edit/{id}',['as' => 'death_edit', 'uses' => 'DeathController@edit']);
			Route::post('/update/{id}',['as' => 'death_update', 'uses' => 'DeathController@update']);
		});	//ARV

	});// Event

	//	Reports
	Route::group(['prefix' => 'reports'], function(){
		Route::get('/form-b/{id?}',['as' =>'form_b','uses' => 'PrintFormsController@form_b']);
		Route::get('/form-c/{id?}',['as' =>'form_c','uses' => 'PrintFormsController@form_c']);
		Route::get('/form-d/{id?}',['as' =>'form_d','uses' => 'PrintFormsController@form_d']);
	});// Password Reset

	//	Item
	Route::group(['prefix' => 'item'], function(){
		Route::get('/',['as' =>'item_list', 'uses' => 'ItemController@index']);
			
		Route::get('/create',['as' =>'item_create','uses' => 'ItemController@create']);
		Route::post('/store',['as' =>'item_store','uses' => 'ItemController@store']);

		Route::get('/edit/{id}',['as' =>'item_edit','uses' => 'ItemController@edit']);
		Route::post('/update/{id}',['as' =>'item_update','uses' => 'ItemController@update']);

		Route::get('/destroy/{id}',['as' =>'item_destroy','uses' => 'ItemController@destroy']);

		/*
		//	Category
		Route::group(['prefix' => 'category'], function(){
			Route::get('/',['as' =>'item_category_list','uses' => 'ItemCategoryController@index']);

			Route::get('/create',['as' =>'item_category_create','uses' => 'ItemCategoryController@create']);
			Route::post('/store',['as' =>'item_category_store','uses' => 'ItemCategoryController@store']);

			Route::get('/edit/{id}',['as' =>'item_category_edit','uses' => 'ItemCategoryController@edit']);
			Route::post('/update/{id}',['as' =>'item_category_update','uses' => 'ItemCategoryController@update']);

		});// Category
		*/

		//	Receive
		Route::group(['prefix' => 'receive'], function(){

app/VCT.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VCT extends Model
{
    protected $table = 'vct';

    public $timestamps = false;

    /*
    Relationships
    */

    public function EnrolmentDemographics()
    {
        return $this->belongsTo('App\EnrolmentDemographics', 'id', 'id');
    }

    public function EnrolmentClinicalAndImmunologic()
    {
        return $this->belongsTo('App\EnrolmentClinicalAndImmunologic', 'id', 'id');
    }

    public function OpportunisticInfections()
    {
        return $this->belongsTo('App\OpportunisticInfections', 'id', 'id');
    }

    /*
    Set Functions
    */

    public function setUiCodeAttribute($value)
    {
        $this->attributes['ui_code'] = strtoupper($value);
    }

    public function setHivPositiveDateRetestAttribute($value)
    {
        if(is_null($value)){
            $value = null;
        }else{
            $value = date('Y-m-d', strtotime($value));
        }

        $this->attributes['hiv_positive_date_retest'] = $value;
    }

    /*
    Get Functions
    */

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getFullName2Attribute()
    {
        return $this->last_name . ', ' . $this->first_name;
    }

    public function getGenderAttribute($value)
    {
        return ucwords($value);
    }

    public function getBirthDateAttribute($value)
    {
        return date('F d, Y', strtotime($value));
    }

    public function getHivPositiveFormatAttribute()
    {
        if($this->hiv_positive){
            return 'Yes';
        }else{
            return 'No';
        }
    }
    /*
    Other Functions
    */

    public function scopeSearchVctList($query, $search)
    {
        $search = '%' . $search . '%';

        return $query->where('first_name', 'LIKE', $search)
                    ->orWhere('last_name', 'LIKE', $search)
                    ->orWhere('ui_code', 'LIKE', $search)
                    ->orWhere('gender', 'LIKE', $search)
                    ->orWhere('vct_date', 'LIKE', $search);
    }

    public function maleCapital()
    {
    	return strtoupper($this->gender);
    }
}

resources/views/hact/enrolment/vct/create.blade.php
@extends('hact.layouts.layout_admin')

@section('content')

	<div class='row'>
		<div class='large-12 columns'>
			<ul class="breadcrumbs">
				<li><a href="{{ route('dashboard') }}">Home</a></li>
				<li><a href="{{ route('vct_index') }}">Voluntary Counseling Testing</a></li>
				<li class="current"><a href="#">New Record</a></li>
			</ul>
		</div>
	</div>

	@include('hact.messages.success')
	@include('hact.messages.error_list')

	<div class="panel">
		<form action="{{ $action }}" method="post">
			<div class="row">
				<div class="large-4 columns">
					<label for="vct_date">Date of VCT:</label>
					<input type="text" id="vct_date" name="vct_date" class="fdatepicker" value="{{ $vct_date }}" placeholder="VCT Date"  readonly="readonly"/> 
				</div>
			</div>

			<fieldset>
	    		<legend>Patient's Name</legend>
				<div class="row">
					<div class="large-4 columns">	
						<label for="first_name">First Name:</label>
						<input type="text" id="first_name" name="first_name" placeholder="First Name" value="{{ $first_name }}">
					</div>
					<div class="large-4 columns">
						<label for="middle_name">Middle Name:</label>
						<input type="text" id="middle_name" name="middle_name" placeholder="Middle Name" value="{{ $middle_name }}">
					</div>
					<div class="large-4 columns">
						<label for="last_name">Last Name:</label>
						<input type="text" id="last_name" name="last_name" placeholder="Last Name" value="{{ $last_name }}">
					</div>
				</div>
			</fieldset>

			<fieldset>
				<legend>Unique Identifier Code</legend>
				<div class="row">
					<div class="large-4 columns">
						<label for="uic_mother_name">First 2 letters of mother's name</label>
						<input type="text" id="uic_mother_name" name="uic_mother_name" minlength="2" maxlength="2" placeholder="A-Z" value="{{ $uic_mother_name }}">
					</div>
					<div class="large-4 columns">
						<label for="uic_father_name">First 2 letters of father's name</label>
						<input type="text" id="uic_father_name" name="uic_father_name" minlength="2" maxlength="2" placeholder="A-Z" value="{{ $uic_father_name }}">
					</div>
					<div class="large-4 columns">
						<label for="uic_birth_order">2-digit birth order</label>
						<input type="text" id="uic_birth_order" name="uic_birth_order" minlength="2" maxlength="2" placeholder="1-0" value="{{ $uic_birth_order }}">
					</div>
				</div>
			</fieldset>


			  <fieldset>
	    		<legend>Mother's Maiden Name</legend>
				<div class="row">
					<div class="large-4 columns">	
						<label for="mother_first_name">First Name:</label>
						<input type="text" id="mother_first_name" name="mother_first_name" placeholder="First Name" value="{{ $mother_first_name }}">
					</div>
					<div class="large-4 columns">
						<label for="mother_middle_name">Middle Name:</label>
						<input type="text" id="mother_middle_name" name="mother_middle_name" placeholder="Middle Name" value="{{ $mother_middle_name }}">
					</div>
					<div class="large-4 columns">
						<label for="mother_last_name">Last Name:</label>
						<input type="text" id="mother_last_name" name="mother_last_name" placeholder="Last Name" value="{{ $mother_last_name }}">
					</div>
				</div>
			</fieldset>

			<fieldset>
		    	<legend>Basic Information</legend>
				<div class="row">
					<div class="large-3 columns">
						<label for="male">Sex:</label>
						<input id="male" name="sex" type="radio" value="male" checked="checked"><label for="male">Male</label>
						<input id="female" name="sex" type="radio" value="female"><label for="female">Female</label><br/>
					</div>

					<div class="large-3 columns">
						<label for="date_of_birth">Date of Birth:</label>
						<input type="text" id="birth_date" class="fdatepicker" name="birth_date" placeholder="Date of Birth" value="{{ $birth_date }}" readonly="readonly">
					</div>

					<div class="large-2 columns">
						<label>Age:</label>
						<input type="text" id="age" name="age" placeholder="Age" value="{{ $age }}" readonly="readonly">
					</div>

					<div class="large-4 columns">&nbsp;</div>
				</div>
				
				<div class="row">
					<div class="large-12 columns">
						<label for="contact_number">Contact Number:</label>
						<input type="text" id="contact_number" name="contact_number" placeholder="Contact Number" value="{{ $contact_number }}">
					</div>
				</div>

			</fieldset>

			<fieldset>
	    		<legend>Address</legend>
				<div class="row">
					<div class="large-12 columns">
						<label for="street">Street:</label>
						<input type="text" id="street" name="street" placeholder="Street" value="{{ $street }}">
					</div>
					<div class="large-12 columns">
						<label for="purok">Purok/Avenue:</label>
						<input type="text" id="purok" name="purok" placeholder="Purok" value="{{ $purok }}">
					</div>
					<div class="large-12 columns">
						<label for="barangay">Barangay:</label>
						<input type="text" id="barangay" name="barangay" placeholder="Barangay" value="{{ $barangay }}">
					</div>
					<div class="large-12 columns">
						<label for="city">City:</label>
						<input type="text" id="city" name="city" placeholder="City" value="{{ $city }}">
					</div>
				</div>
			</fieldset>

			<fieldset>
				<legend>HIV Risks</legend>
				<div class="row">
					<div class="large-6 columns">
						
						<label for="blood_transfusion">
							<input type="checkbox" id="blood_transfusion" name="blood_transfusion" value="1" {{ ($blood_transfusion == 1)? 'checked="checked"' : '' }}> 
							Blood Transfusion(BT) Recipient
						</label>
						<label for="injecting_drug_user">
							<input type="checkbox" id="injecting_drug_user" name="injecting_drug_user" value="1" {{ ($injecting_drug_user == 1)? 'checked="checked"' : '' }}> 
							Injecting Drug User(IDU)
						</label>
						<label for="substance_abuse">
							<input type="checkbox" id="substance_abuse" name="substance_abuse" value="1" {{ ($substance_abuse == 1)? 'checked="checked"' : '' }}> 
							Substance Abuse
						</label>
						<label for="occupational_exposure">
							<input type="checkbox" id="occupational_exposure" name="occupational_exposure" value="1" {{ ($occupational_exposure == 1)? 'checked="checked"' : '' }}> 
							Occupational Exposure(OE)
						</label>
						<!-- disable if occupational_exposure -->
						<div class="occupational_exposure_selection">
							<label for="provided_post_exposure_prophylaxis_yes">Provided Post Exposure Prophylaxis</label>
							<input type="radio" id="provided_post_exposure_prophylaxis_yes" name="provided_post_exposure_prophylaxis" value="1" {{ ($provided_post_exposure_prophylaxis == 1)? 'checked="checked"' : '' }}> 
							<label for="provided_post_exposure_prophylaxis_yes">YES</label>
							<input type="radio" id="provided_post_exposure_prophylaxis_no" name="provided_post_exposure_prophylaxis" value="1" {{ ($provided_post_exposure_prophylaxis == 0)? 'checked="checked"' : '' }}> 
							<label for="provided_post_exposure_prophylaxis_no">NO</label>
						</div>
						<!--  -->
					</div>
					<div class="large-6 columns">
						<label for="sexually_transmitted_infections">
							<input type="checkbox" id="sexually_transmitted_infections" name="sexually_transmitted_infections" value="1" {{ ($sexually_transmitted_infections == 1)? 'checked="checked"' : '' }}> 
							Sexually Transmitted Infections(STI)
						</label>
						<label for="multiple_sexual_partners">
							<input type="checkbox" id="multiple_sexual_partners" name="multiple_sexual_partners" value="1" {{ ($multiple_sexual_partners == 1)? 'checked="checked"' : '' }}> 
							Multiple Sexual Partners
						</label>
						<label for="male_sex_with_other_male">
							<input type="checkbox" id="male_sex_with_other_male" name="male_sex_with_other_male" value="1" {{ ($male_sex_with_other_male == 1)? 'checked="checked"' : '' }}> 
							Male having Sex with other Males(MSM)
						</label>
						<label for="sex_worker_client">
							<input type="checkbox" id="sex_worker_client" name="sex_worker_client" value="1" {{ ($sex_worker_client == 1)? 'checked="checked"' : '' }}> 
							Client of a Sex Worker
						</label>
						<label for="sex_worker">
							<input type="checkbox" id="sex_worker" name="sex_worker" value="1" {{ ($sex_worker == 1)? 'checked="checked"' : '' }}> 
							Sex Worker
						</label>
						<label for="child_of_hiv_infected_mother">
							<input type="checkbox" id="child_of_hiv_infected_mother" name="child_of_hiv_infected_mother" value="1" {{ ($child_of_hiv_infected_mother == 1)? 'checked="checked"' : '' }}> 
							Child of HIV Infected Mother
						</label>
					</div>
				</div>
			</fieldset>
				
			<fieldset>
				<legend>HIV Testing</legend>
				<div class="row">
					<div class="large-5 columns">
						<label for="tested_for_hiv_yes">Tested for HIV?</label>
						<input type="radio" id="tested_for_hiv_yes" name="tested_for_hiv" value="1" {{ ($tested_for_hiv == 1)? 'checked="checked"' : '' }}> 
						<label for="tested_for_hiv_yes">YES</label>
						<input type="radio" id="tested_for_hiv_no" name="tested_for_hiv" value="0" {{ ($tested_for_hiv == 0)? 'checked="checked"' : '' }}> 
						<label for="tested_for_hiv_no">NO</label><br />
						<label for="reason_for_not_testing">Reason for not testing:</label>
						<input type="text" id="reason_for_not_testing" name="reason_for_not_testing" value="{{ $reason_for_not_testing }}" disabled="disabled" />
					</div>
					<div class="large-3 columns">
						<label for="positive_for_hiv_yes">Positive for HIV?</label>
						<input type="radio" id="positive_for_hiv_yes" name="positive_for_hiv" value="1" {{ ($positive_for_hiv == 1)? 'checked="checked"' : '' }}> 
						<label for="positive_for_hiv_yes">YES</label>
						<input type="radio" id="positive_for_hiv_no" name="positive_for_hiv" value="0" {{ ($positive_for_hiv == 0)? 'checked="checked"' : '' }}> 
						<label for="positive_for_hiv_no">NO</label><br />
						<label for="reason_for_not_testing">Date of Re-test:</label>
						<input type="text" id="hiv_positive_date_retest" class="fdatepicker" name="hiv_positive_date_retest" value="{{ $hiv_positive_date_retest }}" disabled="disabled" readonly="readonly" />
					</div>
					<div class="large-4 columns">
						<label for="provide_post_test_counselling_and_hiv_result_yes">Provided Post-test Counseling and HIV Result?</label>
						<input id="provide_post_test_counselling_and_hiv_result_yes" type="radio" name="provide_post_test_counselling_and_hiv_result" value="1" {{ ($provide_post_test_counselling_and_hiv_result == 1)? 'checked="checked"' : '' }}> 
						<label for="provide_post_test_counselling_and_hiv_result_yes">YES</label>
						<input id="provide_post_test_counselling_and_hiv_result_no" type="radio" name="provide_post_test_counselling_and_hiv_result" value="0" {{ ($provide_post_test_counselling_and_hiv_result == 0)? 'checked="checked"' : '' }}>
						<label for="provide_post_test_counselling_and_hiv_result_no">NO</label>
					</div>
				</div>
			</fieldset><br/>

			<div class="row">
				<div class="large-4 columns">&nbsp;</div>
				<div class="large-4 columns">
					<div class="row">
						<div class="large-3 columns">&nbsp;</div>
						<div class="large-6 columns">
							<input type="hidden" name="ui_code" value="">
							{!! csrf_field() !!}
							<input type="hidden" name="id" value="{{ $id }}">
							<input type="submit" class="button alert expand" value="Submit" />
						</div>
						<div class="large-3 columns">&nbsp;</div>
					</div>
				</div>
				<div class="large-4 columns">&nbsp;</div>
			</div>
		</form>
	</div>

<script type="text/javascript">
<?php

if($occupational_exposure == 0){
	echo '$(\'.occupational_exposure_selection\').hide();';
}else{
	echo '$(\'.occupational_exposure_selection\').show();';
}

if($tested_for_hiv == 1){
	echo '$(\'#reason_for_not_testing\').val(\'\').attr(\'disabled\', true);';
}else{
	echo '$(\'#reason_for_not_testing\').attr(\'disabled\', false);';
}

if($positive_for_hiv == 0){
	echo '$(\'#hiv_positive_date_retest\').attr(\'disabled\', false);';
}else{
	echo '$(\'#hiv_positive_date_retest\').val(\'\').attr(\'disabled\', true);';
}

?>




$(function(){
    $("#occupational_exposure").click(function(){
        var status = $(this).is(':checked');

        if(status == true)
        {
        	$('.occupational_exposure_selection').show();
        }
        else
        {
        	$('.occupational_exposure_selection').hide();
        }
    });
});

$(function(){
    $("input[name='tested_for_hiv'").click(function(){
        var value = $(this).val();


        if(value == 1)
        {
        	$('#reason_for_not_testing').val('').attr('disabled', true);
        }
        else
        {
        	$('#reason_for_not_testing').attr('disabled', false);
        }
    });
});

$(function(){
    $("input[name='positive_for_hiv'").click(function(){
        var value = $(this).val();


        if(value == 1)
        {
        	$('#hiv_positive_date_retest').val('').attr('disabled', true);
        }
        else
        {
        	$('#hiv_positive_date_retest').attr('disabled', false);
        }
    });
});
</script>
@endsection

resources/views/hact/enrolment/vct/index.blade.php
@extends('hact.layouts.layout_admin')

@section('content')

	<div class='row'>
		<div class='large-7 columns'>
			<ul class="breadcrumbs">
				<li><a href="{{ route('dashboard') }}">Home</a></li>
				<li class="current"><a href="#">Voluntary Counseling Testing</a></li>
			</ul>
		</div>
		<div class='large-5 columns'>
			<form>
				<div class="row">
					<div class="large-12 columns">
						<div class="row collapse">
							<div class="small-9 columns">
								<input name="search" type="text" placeholder="Search" value="{{ $search }}">
							</div>
					    	<div class="small-3 columns">
					      		<button type="submit" class="button alert postfix"><i class="fa fa-search"></i></buatton>
					    	</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>

	<div class='row'>
		<div class='large-12 columns'>
			@include('hact.messages.success')
			@include('hact.messages.error_list')
			{!! str_replace('/?', '?', $patients->appends($pagination)->render()) !!}
			<table width="100%">
				<thead>
				<tr>
					<th width="5%"></th>	
					<th width="20%"><a href="{{ $ui_code_sort }}">UI Code</a></th>
					<th width="35%"><a href="{{ $patient_name_sort }}">Name</a></th>
					<th width="10%"><a href="{{ $gender_sort }}">Gender</a></th>
					<th width="15%"><a href="{{ $hiv_positive_sort }}">HIV Positive</a></th>
					<th width="15%"><a href="{{ $vct_date_sort }}">VCT Date</a></th>
				</tr>
				</thead>
				<tbody>
				@foreach($patients as $patient)
				<tr>
					<td>
						<a href="{{ route('vct_edit',$patient->id) }}" title="Edit VCT Record"><i class="fa fa-edit"></i></a>
					</td>
					<td>{{ $patient->ui_code }}</td>
					<td>{{ $patient->last_name . ', ' . $patient->first_name . ' ' . $patient->middle_name . '.' }}</td>
					<td>{{ $patient->gender }}</td>
					<td>{{ $patient->hiv_positive_format }}</td>
					<td>{{ $patient->vct_date }}</td>
				</tr>
				@endforeach	
				</tbody>
			</table>
			{!! str_replace('/?', '?', $patients->appends($pagination)->render()) !!}
		</div>
	</div>

@endsection